const teamData = [
  {
    id: 1,
    imagePath: "/images/team/kirtiMam.jpg",
    name: "Dr. Kirti Dorshetwar",
    designation: "Faculty Coordinator",
    email: "kdorshetwar@iiitn.ac.in",
    linkedinLink: "https://www.linkedin.com/in/dr-kirti-dorshetwar-44a83374",
    instagramLink: "",
    githubLink: "",
  },
  {
    id: 2,
    imagePath: "/images/team/yashMishra.jpeg",
    name: "Yash Mishra",
    designation: "Wing coordinator",
    email: "bt20ece057@iiitn.ac.in",
    linkedinLink: "https://www.linkedin.com/in/yash-mishra-649090216/",
    instagramLink: "https://www.instagram.com/__yashmishra09__/",
    githubLink: "https://github.com/Geekboieyash",
  },
  {
    id: 3,
    imagePath: "/images/team/vipraNagaich.jpg",
    name: "Vipra Nagaich",
    designation: "Content & Anchoring",
    email: "bt20ece062@iiitn.ac.in",
    linkedinLink: "https://www.linkedin.com/in/vipra-nagaich-b24a4920b",
    instagramLink: "",
    githubLink: "",
    twitterLink: "https://twitter.com/WayGyanixx",
  },
  {
    id: 4,
    imagePath: "/images/team/sanilSattarkar.jpg",
    name: "Sanil Sattarkar",
    designation: "Design",
    email: "bt20ece001@iiitn.ac.in",
    linkedinLink: "https://www.linkedin.com/in/sanil-sattarkar-529132202/",
    instagramLink: "https://www.instagram.com/sanil_0205/",
    githubLink: "https://github.com/sanils2002",
  },
  {
    id: 5,
    imagePath: "/images/team/kushagraSharma.png",
    name: "Kushagra Sharma",
    designation: "Social Media Outreach",
    email: "bt20ece069@iiitn.ac.in",
    linkedinLink: "https://www.linkedin.com/in/imkushagra12",
    instagramLink: "https://www.instagram.com/imkushagra12",
    githubLink: "",
  },
  {
    id: 6,
    imagePath: "/images/team/bhaveshChaudhari.webp",
    name: "Bhavesh Chaudhari",
    designation: "Web Development",
    email: "bhic2030@gmail.com",
    linkedinLink: "https://www.linkedin.com/in/bhavesh-chaudhari-bb4966208/",
    instagramLink: "https://www.instagram.com/bhaveshc0",
    githubLink: "https://github.com/bhavesh-chaudhari",
    twitterLink: "https://twitter.com/bhaveshc0",
  },
  {
    id: 7,
    imagePath: "/images/team/deepPanchani.jpg",
    name: "Deep Panchani",
    designation: "Web Design",
    email: "deeppanchani0219@gmail.com",
    linkedinLink: "https://www.linkedin.com/in/deep-panchani-7805861b5/",
    instagramLink: "https://www.instagram.com/deepanchani/",
    githubLink: "https://github.com/deeppanchani",
  },
  {
    id: 8,
    imagePath: "/images/team/aditiYadav.jpg",
    name: "Aditi Yadav",
    designation: "Content & Anchoring",
    email: "bt20cse055@iiitn.ac.in",
    linkedinLink: "https://www.linkedin.com/in/aditiyadav03/",
    instagramLink: "https://www.instagram.com/aditiiyadavv14/",
    githubLink: "https://github.com/aditi1403",
  },
  {
    id: 9,
    imagePath: "/images/team/ayushChaurasia.jpeg",
    name: "Ayush Chaurasia",
    designation: "Social Media Outreach",
    email: "ayush220802@gmail.com",
    linkedinLink: "https://www.linkedin.com/in/ayush-chaurasia-ab4192201",
    instagramLink: "https://www.instagram.com/mr__ayush_2.0/",
    githubLink: "https://github.com/Er-Ayush",
  },
  {
    id: 10,
    imagePath: "/images/team/lalithaTanmai.jpg",
    name: "Lalitha Tanmai",
    designation: "Design",
    email: "bt20cse154@iiitn.ac.in",
    linkedinLink: "https://www.linkedin.com/in/lalitha-tanmai-32b627211/",
    instagramLink: "https://www.instagram.com/tanmai_vaddiparthy/",
    githubLink: "",
  },
  {
    id: 11,
    imagePath: "/images/team/rohanUdhwani.jpg",
    name: "Rohan Udhwani",
    designation: "Video Editing",
    email: "bt21cse092@iiitn.ac.in",
    linkedinLink: "https://www.linkedin.com/in/rohanudhwani",
    instagramLink: "https://www.instagram.com/rohanudhwanii/",
    githubLink: "",
  },
  {
    id: 12,
    imagePath: "/images/team/yashOjha.jpg",
    name: "Yash Ojha",
    designation: "Social Media Outreach",
    email: "yashojha.yo.55@gmail.com",
    linkedinLink: "https://www.linkedin.com/in/yash-ojha-323969206",
    instagramLink: "https://www.instagram.com/yash_ojha7/",
    githubLink: "https://github.com/yashojha07",
  },
  {
    id: 13,
    imagePath: "/images/team/sunnyDubey.jpg",
    name: "Sunny Dubey",
    designation: "Content",
    email: "bt20cse038@iiitn.ac.in",
    linkedinLink: "",
    instagramLink: "https://www.instagram.com/sunnyrdubey/",
    githubLink: "",
    twitterLink:
      "https://twitter.com/SunnyRDubey1?t=yNQXxfRbeRDw9yfPYmZgTA&s=08",
  },
  {
    id: 14,
    imagePath: "/images/team/shubhasriTadepalli.jpeg",
    name: "Shubhasri Tadepalli",
    designation: "Design",
    email: "shubhasritadepalli@gmail.com",
    linkedinLink: "https://www.linkedin.com/in/shubhasri-tadepalli-458981204/",
    instagramLink: "https://www.instagram.com/shubha_sri_tadepalli",
    githubLink: "https://github.com/shubhasri-1234",
  },
  {
    id: 15,
    imagePath: "/images/team/vishalGoyal.png",
    name: "Vishal Goyal",
    designation: "Video Editing",
    email: "",
    linkedinLink: "https://www.linkedin.com/in/vishal-goyal-00195b1b7",
    instagramLink: "https://www.instagram.com/viishal_goyal/",
    githubLink: "https://github.com/goyalvishal03",
  },
  {
    id: 16,
    imagePath: "/images/team/sanketTeli.png",
    name: "Sanket Teli",
    designation: "Video Editing",
    email: "bt21ece080@iiitn.ac.in",
    linkedinLink: "https://www.linkedin.com/in/sanket-teli-446113229/",
    instagramLink: "https://www.instagram.com/sa.nket__05_10/",
    githubLink: "",
  },
  {
    id: 17,
    imagePath: "/images/team/adityaSengar.png",
    name: "Aditya Sengar",
    designation: "Design",
    email: "bt20cse091@gmail.com",
    linkedinLink: "",
    instagramLink: "https://www.instagram.com/editya_singh/",
    githubLink: "",
  },
  {
    id: 18,
    imagePath: "/images/team/mayurAgrawal.jpg",
    name: "Mayur Agrawal",
    designation: "Video Editing",
    email: "agrawalmayur943@gmail.com",
    linkedinLink: "https://www.linkedin.com/in/mayur-agrawal-330098223",
    instagramLink: "https://www.instagram.com/mayur_.18/",
    githubLink: "",
  },
];

export default teamData;
